name: Linting & Style Checks
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up Python 3.11
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: .github/requirements.txt
      - name: Install Python dependencies
        run: |
          pip install -r .github/requirements.txt
      - name: Lint and Format Check
        run: |
          # Check format. To fix, run "ruff format ."
          ruff format --diff .
          # Check PEP8 violations, logic/correctness errors, and sort imports. To fix, run "ruff check --fix ."
          ruff check --diff .
